[project]
name = "mcp-on-streamlit"
version = "0.1.0"
description = "MCP Client on Streamlit Application"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.55.0",
    "mcp>=1.10.1",
    "python-dotenv>=1.1.1",
    "streamlit>=1.46.1",
]
